- name: Sample Workflow
  triggers:
    - app_start: "example.exe"
    - at_time: "18:00"
    - cpu_above: 80
    - network_above: 100
  actions:
    - launch: "notepad.exe"
    - wait: 2
    - notify: "Notepad launched"
    - kill: "calc.exe"
